### ISSUE TITLE
Typed static property `App\Nova\Settings::$keyName` must not be accessed before initialization

### ISSUE THREAD

**Issue by muhghazaliakbar** [Muetze42/nova-single-resource#10]
![Screenshot 2022-12-05 at 18 23 04](https://user-images.githubusercontent.com/8321936/205613653-ad909d39-6750-4ea9-bf2e-597980226864.png)

Here is my migration:
```php
<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('settings', function (Blueprint $table) {
            $table->id();
            $table->string('key')->unique('index');
            $table->text('value');
            $table->timestamps();
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('settings');
    }
};
```

Everything else is default generated by `php artisan nova:single-resource Settings` command

**Comment by Muetze42** [comment]
What exactly is in the log?

**Comment by muhghazaliakbar** [comment]
@Muetze42 Here's the complete log:
```
[2022-12-08 11:47:19] local.ERROR: Typed static property App\Nova\Settings::$keyName must not be accessed before initialization {"userId":1,"exception":"[object] (Error(code: 0): Typed static property App\\Nova\\Settings::$keyName must not be accessed before initialization at /Users/muhghazaliakbar/Projects/sks/webdesa/vendor/norman-huth/nova-single-resource/src/Traits/ResourceTrait.php:84)
[stacktrace]
#0 /Users/muhghazaliakbar/Projects/sks/webdesa/vendor/laravel/nova/src/PerformsQueries.php(30): App\\Nova\\Settings::indexQuery(Object(Laravel\\Nova\\Http\\Requests\\ResourceIndexRequest), Object(Illuminate\\Database\\Eloquent\\Builder))
#1 /Users/muhghazaliakbar/Projects/sks/webdesa/vendor/laravel/framework/src/Illuminate/Database/Concerns/BuildsQueries.php(502): Laravel\\Nova\\Resource::Laravel\\Nova\\{closure}(Object(Illuminate\\Database\\Eloquent\\Builder))
#2 /Users/muhghazaliakbar/Projects/sks/webdesa/vendor/laravel/nova/src/PerformsQueries.php(31): Illuminate\\Database\\Eloquent\\Builder->tap(Object(Closure))
#3 /Users/muhghazaliakbar/Projects/sks/webdesa/vendor/laravel/nova/src/Query/Builder.php(119): Laravel\\Nova\\Resource::buildIndexQuery(Object(Laravel\\Nova\\Http\\Requests\\ResourceIndexRequest), Object(Illuminate\\Database\\Eloquent\\Builder), NULL, Array, Array, NULL)
#4 [internal function]: Laravel\\Nova\\Query\\Builder->Laravel\\Nova\\Query\\{closure}(Object(Illuminate\\Database\\Eloquent\\Builder))
#5 /Users/muhghazaliakbar/Projects/sks/webdesa/vendor/laravel/nova/src/Query/Builder.php(310): call_user_func(Object(Closure), Object(Illuminate\\Database\\Eloquent\\Builder))
#6 /Users/muhghazaliakbar/Projects/sks/webdesa/vendor/laravel/framework/src/Illuminate/Collections/Traits/EnumeratesValues.php(236): Laravel\\Nova\\Query\\Builder->Laravel\\Nova\\Query\\{closure}(Object(Closure), 0)
#7 /Users/muhghazaliakbar/Projects/sks/webdesa/vendor/laravel/nova/src/Query/Builder.php(311): Illuminate\\Support\\Collection->each(Object(Closure))
#8 /Users/muhghazaliakbar/Projects/sks/webdesa/vendor/laravel/framework/src/Illuminate/Database/Concerns/BuildsQueries.php(502): Laravel\\Nova\\Query\\Builder->Laravel\\Nova\\Query\\{closure}(Object(Illuminate\\Database\\Eloquent\\Builder))
#9 /Users/muhghazaliakbar/Projects/sks/webdesa/vendor/laravel/nova/src/Query/Builder.php(317): Illuminate\\Database\\Eloquent\\Builder->tap(Object(Closure))
#10 /Users/muhghazaliakbar/Projects/sks/webdesa/vendor/laravel/nova/src/Query/Builder.php(220): Laravel\\Nova\\Query\\Builder->applyQueryCallbacks(Object(Illuminate\\Database\\Eloquent\\Builder))
#11 /Users/muhghazaliakbar/Projects/sks/webdesa/vendor/laravel/nova/src/Http/Requests/ResourceIndexRequest.php(21): Laravel\\Nova\\Query\\Builder->paginate(25)
#12 /Users/muhghazaliakbar/Projects/sks/webdesa/vendor/laravel/nova/src/Http/Resources/IndexViewResource.php(19): Laravel\\Nova\\Http\\Requests\\ResourceIndexRequest->searchIndex()
#13 /Users/muhghazaliakbar/Projects/sks/webdesa/vendor/laravel/nova/src/Http/Resources/Resource.php(41): Laravel\\Nova\\Http\\Resources\\IndexViewResource->toArray(Object(Laravel\\Nova\\Http\\Requests\\ResourceIndexRequest))
#14 /Users/muhghazaliakbar/Projects/sks/webdesa/vendor/laravel/nova/src/Http/Controllers/ResourceIndexController.php(19): Laravel\\Nova\\Http\\Resources\\Resource->toResponse(Object(Laravel\\Nova\\Http\\Requests\\ResourceIndexRequest))
#15 /Users/muhghazaliakbar/Projects/sks/webdesa/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): Laravel\\Nova\\Http\\Controllers\\ResourceIndexController->__invoke(Object(Laravel\\Nova\\Http\\Requests\\ResourceIndexRequest), 'settings')
#16 /Users/muhghazaliakbar/Projects/sks/webdesa/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(43): Illuminate\\Routing\\Controller->callAction('__invoke', Array)
#17 /Users/muhghazaliakbar/Projects/sks/webdesa/vendor/laravel/framework/src/Illuminate/Routing/Route.php(260): Illuminate\\Routing\\ControllerDispatcher->dispatch(Object(Illuminate\\Routing\\Route), Object(Laravel\\Nova\\Http\\Controllers\\ResourceIndexController), '__invoke')
#18 /Users/muhghazaliakbar/Projects/sks/webdesa/vendor/laravel/framework/src/Illuminate/Routing/Route.php(205): Illuminate\\Routing\\Route->runController()
#19 /Users/muhghazaliakbar/Projects/sks/webdesa/vendor/laravel/framework/src/Illuminate/Routing/Router.php(798): Illuminate\\Routing\\Route->run()
#20 /Users/muhghazaliakbar/Projects/sks/webdesa/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#21 /Users/muhghazaliakbar/Projects/sks/webdesa/vendor/laravel/nova/src/Http/Middleware/Authorize.php(18): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#22 /Users/muhghazaliakbar/Projects/sks/webdesa/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Laravel\\Nova\\Http\\Middleware\\Authorize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#23 /Users/muhghazaliakbar/Projects/sks/webdesa/vendor/laravel/nova/src/Http/Middleware/BootTools.php(20): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#24 /Users/muhghazaliakbar/Projects/sks/webdesa/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Laravel\\Nova\\Http\\Middleware\\BootTools->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#25 /Users/muhghazaliakbar/Projects/sks/webdesa/vendor/laravel/nova/src/Http/Middleware/DispatchServingNovaEvent.php(33): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#26 /Users/muhghazaliakbar/Projects/sks/webdesa/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Laravel\\Nova\\Http\\Middleware\\DispatchServingNovaEvent->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#27 /Users/muhghazaliakbar/Projects/sks/webdesa/vendor/inertiajs/inertia-laravel/src/Middleware.php(92): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#28 /Users/muhghazaliakbar/Projects/sks/webdesa/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Inertia\\Middleware->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#29 /Users/muhghazaliakbar/Projects/sks/webdesa/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(50): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#30 /Users/muhghazaliakbar/Projects/sks/webdesa/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#31 /Users/muhghazaliakbar/Projects/sks/webdesa/vendor/laravel/framework/src/Illuminate/Auth/Middleware/Authenticate.php(44): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#32 /Users/muhghazaliakbar/Projects/sks/webdesa/vendor/laravel/nova/src/Http/Middleware/Authenticate.php(31): Illuminate\\Auth\\Middleware\\Authenticate->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#33 /Users/muhghazaliakbar/Projects/sks/webdesa/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Laravel\\Nova\\Http\\Middleware\\Authenticate->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#34 /Users/muhghazaliakbar/Projects/sks/webdesa/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(78): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#35 /Users/muhghazaliakbar/Projects/sks/webdesa/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#36 /Users/muhghazaliakbar/Projects/sks/webdesa/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#37 /Users/muhghazaliakbar/Projects/sks/webdesa/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#38 /Users/muhghazaliakbar/Projects/sks/webdesa/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(121): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#39 /Users/muhghazaliakbar/Projects/sks/webdesa/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(64): Illuminate\\Session\\Middleware\\StartSession->handleStatefulRequest(Object(Illuminate\\Http\\Request), Object(Illuminate\\Session\\Store), Object(Closure))
#40 /Users/muhghazaliakbar/Projects/sks/webdesa/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Session\\Middleware\\StartSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#41 /Users/muhghazaliakbar/Projects/sks/webdesa/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#42 /Users/muhghazaliakbar/Projects/sks/webdesa/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#43 /Users/muhghazaliakbar/Projects/sks/webdesa/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(67): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#44 /Users/muhghazaliakbar/Projects/sks/webdesa/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#45 /Users/muhghazaliakbar/Projects/sks/webdesa/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#46 /Users/muhghazaliakbar/Projects/sks/webdesa/vendor/laravel/framework/src/Illuminate/Routing/Router.php(799): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#47 /Users/muhghazaliakbar/Projects/sks/webdesa/vendor/laravel/framework/src/Illuminate/Routing/Router.php(776): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))
#48 /Users/muhghazaliakbar/Projects/sks/webdesa/vendor/laravel/framework/src/Illuminate/Routing/Router.php(740): Illuminate\\Routing\\Router->runRoute(Object(Illuminate\\Http\\Request), Object(Illuminate\\Routing\\Route))
#49 /Users/muhghazaliakbar/Projects/sks/webdesa/vendor/laravel/framework/src/Illuminate/Routing/Router.php(729): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))
#50 /Users/muhghazaliakbar/Projects/sks/webdesa/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(190): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))
#51 /Users/muhghazaliakbar/Projects/sks/webdesa/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}(Object(Illuminate\\Http\\Request))
#52 /Users/muhghazaliakbar/Projects/sks/webdesa/vendor/laravel/nova/src/Http/Middleware/ServeNova.php(23): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#53 /Users/muhghazaliakbar/Projects/sks/webdesa/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Laravel\\Nova\\Http\\Middleware\\ServeNova->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#54 /Users/muhghazaliakbar/Projects/sks/webdesa/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#55 /Users/muhghazaliakbar/Projects/sks/webdesa/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(31): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#56 /Users/muhghazaliakbar/Projects/sks/webdesa/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\ConvertEmptyStringsToNull->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#57 /Users/muhghazaliakbar/Projects/sks/webdesa/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#58 /Users/muhghazaliakbar/Projects/sks/webdesa/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(40): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#59 /Users/muhghazaliakbar/Projects/sks/webdesa/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\TrimStrings->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#60 /Users/muhghazaliakbar/Projects/sks/webdesa/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#61 /Users/muhghazaliakbar/Projects/sks/webdesa/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#62 /Users/muhghazaliakbar/Projects/sks/webdesa/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(86): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#63 /Users/muhghazaliakbar/Projects/sks/webdesa/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#64 /Users/muhghazaliakbar/Projects/sks/webdesa/vendor/laravel/framework/src/Illuminate/Http/Middleware/HandleCors.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#65 /Users/muhghazaliakbar/Projects/sks/webdesa/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Http\\Middleware\\HandleCors->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#66 /Users/muhghazaliakbar/Projects/sks/webdesa/vendor/laravel/framework/src/Illuminate/Http/Middleware/TrustProxies.php(39): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#67 /Users/muhghazaliakbar/Projects/sks/webdesa/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Http\\Middleware\\TrustProxies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#68 /Users/muhghazaliakbar/Projects/sks/webdesa/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#69 /Users/muhghazaliakbar/Projects/sks/webdesa/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(165): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#70 /Users/muhghazaliakbar/Projects/sks/webdesa/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(134): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#71 /Users/muhghazaliakbar/Projects/sks/webdesa/public/index.php(52): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#72 /Users/muhghazaliakbar/.composer/vendor/laravel/valet/server.php(234): require('/Users/muhghaza...')
#73 {main}
"} 
```

**Comment by Muetze42** [comment]
Add this in your Nova resource or update the package:

```php
    public function __construct($resource = null)
    {
        $this->bootResourceTrait();
        parent::__construct($resource);
    }
```

**Comment by muhghazaliakbar** [comment]
@Muetze42 Awesome it's working!
